name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - beta*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18.3'

    - name: Build
      run: go build .

    - name: Test With Coverage
      run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

    - name: Run Vet & Lint
      run: |
        go vet ./...
